### PR TITLE
add Ruby head and YJIT to CI

### PR DESCRIPTION
**Pull request by reeganviljoen**
### What are you trying to accomplish?

Add ruby head to CI as well as YJIT as discussed in #2010 by me and @joelhawksley 

### Anything you want to highlight for special attention from reviewers?
Ruby head seems to have to be failing on CI which needs further investigation into whether it is a ruby bug or if it really is a breaking change

### CODE REVIEW

**Comment by joelhawksley** [comment]
@reeganviljoen mind turning this off for Rails 6.1? Let's just test against 7.x.

**Comment by reeganviljoen** [comment]
@joelhawksley I removed the new addition with rails 6.1

**Comment by joelhawksley** [comment]
@reeganviljoen thanks! It looks like we still need to exclude a couple of 6.1 builds. For 7.0 and 7.1, it looks like we have one legitimate failure. I'd be happy to look into it, but I'm unable to push to your branch.

**Comment by reeganviljoen** [comment]
@joelhawksley I have updated my branch protection rules to allow you to push, and I have fixed removed the last few 6.1 builds

**Comment by reeganviljoen** [comment]
@joelhawksley any new feedback ?

**Comment by reeganviljoen** [comment]
@joelhawksley I would like to investigate the failing ruby head tests on CI to do this however I need some failing CI tests, now I can either create a branch of of this, or work create a branch from the main branch once its merged.I am happy with which ever option suites the team better. If I work of a branch based on this branch however I just need to finalise any changes on this branch so I can avoid syncing changes between two branches all the time. Can you please leave your preferred option when ever you are able too

**Comment by reeganviljoen** [comment]
@joelhawksley gentle nudge any news

**Pull request closed without merging**
