### PR TITLE
chore: Bump activesupport version

### PR DESCRIPTION
**Pull request by DRBragg**
### What are you trying to accomplish?

Re-opening #1553 

Changes in #1550 and #1536 caused `view_component` to no longer be compatible with Rails < 5.2. This PR updates the `.gemspec` file to require `activesupport` version >= 5.2 so folks know about the compatibility issue when installing/updating.  I also updated the compatibility documentation to reflect this.

### CODE REVIEW

**Comment by DRBragg** [comment]
@joelhawksley I just want to make sure this PR is good. I know it's not a high priority but I just want to make sure there's no additional action needed from me before I completely remove it from my to do list.

**Review by Spone — APPROVED** [review]

**Comment by Spone** [comment]
But maybe we should target the v3 branch @joelhawksley?

**Comment by DRBragg** [comment]
> But maybe we should target the v3 branch @joelhawksley?

It should probably have targeted the main branch since view_component hasn't been compatible with Rails < 5.2 since version 2.72.0 but you can still install 2.78.0 in an app with no bundler errors. You'll only know there'a an issue when you start rendering components and you sift through the backtraces...

**Comment by joelhawksley** [comment]
@DRBragg That's fair. I figured we'd be shipping v3 soon enough for it not to matter. (We're prepping the branch here: https://github.com/ViewComponent/view_component/compare/v3?expand=1).

I'd be happy to land this change sooner though. Want to reopen against main?

**Comment by DRBragg** [comment]
> @DRBragg That's fair. I figured we'd be shipping v3 soon enough for it not to matter. (We're prepping the branch here: https://github.com/ViewComponent/view_component/compare/v3?expand=1).
> 
> I'd be happy to land this change sooner though. Want to reopen against main?

Sure. Forgive my ignorance on this but to reopen against main would that just be opening a new PR with the same branch but just target main?

**Comment by joelhawksley** [comment]
@DRBragg I'm not sure, actually! I'm open to whatever you suggest.

**Comment by DRBragg** [comment]
@joelhawksley Opened #1609 but let me know if that wont work or if you need me to do something additional. Thanks!

**Pull request merged**
