### PR TITLE
Add one more require to docs

### PR DESCRIPTION
**Pull request by kalashnikovisme**
The changed example does not work without added line

### What are you trying to accomplish?

It's a little docs issue.

### What approach did you choose and why?

I want every example in the documentation to work.

### Anything you want to highlight for special attention from reviewers?

### CODE REVIEW

**Review by joelhawksley — APPROVED** [review]
Mind adding a changelog?

**Comment by kalashnikovisme** [comment]
Yeah! I'm going to provide it right now.

**Comment by kalashnikovisme** [comment]
I see failed CI jobs. Looks like it's not related with my changes.

**Review by Spone — APPROVED** [review]
Good catch!

**Pull request merged**
