### PR TITLE
Automate changelog maintenance as part of `script/release`

### PR DESCRIPTION
**Pull request by rmacklin**
### Summary

This PR is an attempt to address #1182 using the approach mentioned in https://github.com/github/view_component/issues/1182#issuecomment-988470999

### CODE REVIEW

**Comment by boardfish** [comment]
Hi @rmacklin! I'd also like to contribute here - I've been working towards a solution in #1250. I think it would be ideal to choose a dependency here so that we can effectively just set it and forget it. So far, I've looked into several solutions including `github_changelog_generator`, `release-drafter`, and `git-chglog`. None of those met all of our needs, which seem to be:

- it produces correct output (`github_changelog_generator` didn't meet this)
- it is efficient and doesn't use more CI time than it should (`github_changelog_generator` didn't meet this)
- it adds to CHANGELOG.md
  `release-drafter` didn't meet this as I hoped - it generates the documentation for a single GitHub release, which it also provides to a CI pipeline as text. We'd need more manual logic to add that to the top of `CHANGELOG.md` at an appropriate time, so we could probably only do that per release rather than per merged PR. The solution given in this PR so far seems to work the same way.
- it credits those responsible for the work (`git-chglog` didn't meet this, but I have an issue open. There's been no response yet.)

We may need an original solution as you've devised here, but if you're able to find a suitable dependency that can fulfill the same role, I feel that may be preferable.

**Comment by rmacklin** [comment]
Yeah, I feel you. My proposal was effectively to make `git` itself be that dependency. I did wrap it with a few lines of ruby scripting, but it still ends up being, in my opinion, very little to maintain. (Thus, I think it could still be "set it and forget it". But it also opens the door for more flexibility down the road, should we want that, compared to a purely templated changelog. As an example, the script could easily be altered to handle skipping commits that contain `[skip changelog]` or other logic.)

**Comment by boardfish** [comment]
I've closed #1250 - seems like the way #1182 is going, we may need a middle ground between this and that approach.

I like where discussion is going with this - I think it's leading to a changelog solution that might be transferable across a lot of projects.

**Comment by rmacklin** [comment]
Closing as stale

**Pull request closed without merging**
