### PR TITLE
docs/index: add Workbrew.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
👋🏻 Thanks for the great project!

We're also using ViewComponents over here and ❤️ them.

### CODE REVIEW

**Comment by reeganviljoen** [comment]
@MikeMcQuaid great to hear 🎉 ,I see you have a CI failure that can be fixed by adding an entry to the changelog

**Comment by joelhawksley** [comment]
@reeganviljoen I'm fine merging these without changelogs. Maybe we can relax the requirement to exclude changes to that markdown file?

**Comment by MikeMcQuaid** [comment]
Thanks @reeganviljoen and @joelhawksley!

Hope you're well @joelhawksley, it's been a wee while!

**Comment by reeganviljoen** [comment]
@joelhawksley i think thats fair, do we do that as a process thing or by making an exclusion in the actions check ?

**Pull request merged**
