### PR TITLE
Add slot unwrapping API

### PR DESCRIPTION
**Pull request by camertron**
Fixes https://github.com/ViewComponent/view_component/issues/1737

### What are you trying to accomplish?

This PR introduces an API for retrieving the underlying component instance inside `ViewComponent::Slot`s. At the moment, getting a reference to the underlying component necessitates using `instance_variable_get`, eg:

```ruby
class MyComponent < ViewComponent::Base
  renders_one :header, HeaderComponent
  renders_many :items, ItemComponent
end

render(MyComponent.new) do |component|
  # returns an instance of ViewComponent::Slot
  component.header

  # returns an instance of HeaderComponent
  component.header.instance_variable_get(:@__vc_component_instance)
end
```

This is awkward. The `@__vc_component_instance` is private and not designed to be accessed outside the `Slot` class.

### What approach did you choose and why?

I propose the following API:

```ruby
render(MyComponent.new) do |component|
  # returns an instance of HeaderComponent
  component.header_instance

  # returns an array of ItemComponent instances
  component.item_instances
end
```

This works for any component slot. For lambda slots, the `*_instance` methods are not defined.

### Anything you want to highlight for special attention from reviewers?

Is the `_instance` suffix the best naming? Maybe `_component` would be better? Open to suggestions 😄

### CODE REVIEW

**Comment by Spone** [comment]
Re: the suffix I think `_component` is clearer than `_instance` (... of what?)

Anyway I think both are more explicit than the initial `unwrap` idea.

**Comment by BlakeWilliams** [comment]
Just writing this down real quick since I don't have the time to write up a longer response, but I'm still on the fence here. I get the intention behind this change, but I also think we should try to avoid having another API for accessing slots in addition to the APIs we already have.

**Comment by Spone** [comment]
Yeah my comment was only about the naming.

I've never had a use case for this in the projects I'm working on, so I'm not especially for this addition.

I reckon it adds another layer of complexity to the Slots which are already the most complex part of ViewComponent (in terms of usage I mean).

**Comment by camertron** [comment]
Thanks for your feedback @Spone and @BlakeWilliams! I agree it adds a bit more complexity to an already complex feature, and I also agree there are limited occasions for use. I have personally run into a similar issue to the one the OP describes in https://github.com/ViewComponent/view_component/issues/1737 (comparing two wrapped component instances). I've also had occasion to unwrap slots when attempting to forward them to other components, and while debugging. In other words, I think the framework needs some way of unwrapping slots. If this isn't it, that's fine, but I would like to figure out the right approach.

**Comment by reeganviljoen** [comment]
I would like to agree with @camertron, I have also needed access to the base component in a slot via unwrapping when I was attempting to add #1620 , this may even unblock it and give us the chance at re-attempting to add it, however due to the uncertainty may I suggest we add this as an optional experimental feature similar to how inline templates where added until we can see if it really is useful in the real world

**Comment by camertron** [comment]
We talked about this internally and have decided removing the `Slot` wrapper is the better way forward 👍

**Pull request closed without merging**
